# Enable C++
language: cpp

# Compiler
compiler: gcc

# Build steps
jobs:
  include:
    - stage: build
      script:
        - rm -rf build
        - mkdir build
        - cd build
        - pwd && cmake ..
        - pwn && make
    - stage: test
      script:
        - pwd && make test