dist: trusty
sudo: required

# Enable C++
language: cpp

# Compiler
compiler: gcc

addons:
  sonarcloud:
    organization: "Algodat I"
    token:
      secure: "BDNjYLbMjulBxWJvT0vPBWkj+ByUuq/D8RYC5wtsdQsnb7aFtF/72zHsxfsnbjRsRMd0JU2GLTLBpHKn8/5pyTAMwar6VzXptXJfYBhrv/xr2S1WdYezON4sjs05VXrqW8+XVgtp+h0AqSDWeWfFbf2EFLOC+kjkKcaWz2fcztyu0TDCjRCf+LpTYFuonCdoAzMv73xgG4mM8MbFsvTtzM6aK4eXoxHbjCvNGNHvD6frHGkGQ8XD5CCutx8avYMBX7HX+OrTQ9phuE38JqwxqUOTNIGeTuW8YgF43VI2Fm660gLa8ARyYBgXH16mgPLYpBWcVbpNFYpUQX/yMer6fTqJLD5PWwjV3cbmlqiknP4nBv/WS22cUz7BR/eadzg8zPOoxPg7AyA/WlOjAxXAkLF24sZF0DvdRIUDzZMV3x7eVBa2HarAZDYT5YZ8utESndgEkBrj5GXFEagZLz/KilKcumJsmuamEbUjcehkai6cDLMEarofggOQPslNgcfKgNjqggjSRQ9lBsmG+j7r3Ck95Y7CKD8BcKXKL0yWEp3H68qLyVFo/QZpr0I8vbVyuVqYXV3XsWjKjz7+WlUY0AJgVxVlGjKtXQvkFllyqAdsk4y3FABFoAGTXRjlvjWlTJMOixC2D0ElxyDib3ld7rjYIuhPyRbFhdVq5n6VKCo="

# Build steps
script:
  - rm -rf build
  - mkdir build
  - cd build
  - pwd && cmake ..
  - pwd && make
  - pwd && make test
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'