dist: trusty
sudo: required

# Enable C++
language: cpp

# Compiler
compiler: gcc

addons:
  sonarcloud:
    organization: "algodat1"

# Build steps
script:
  - rm -rf build
  - mkdir build
  - cp sonar-project.properties build/
  - cd build
  - pwd && cmake ..
  - pwd && make
  - pwd && make test
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.sonar/cache'