dist: trusty
sudo: required

# Enable C++
language: cpp

# Compiler
compiler: gcc

# Build steps
script:
  - rm -rf build
  - mkdir build
  - cp sonar-project.properties build/
  - cd build
  - pwd && cmake ..
  - pwd && make
  - pwd && make test
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.projectKey=cs.hm.edu.algodat.bullshitking.avltree -Dsonar.sources=../avltree -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=algodat1 -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.sonar/cache'