dist: trusty
sudo: required

# Enable C++
language: cpp

# Compiler
compiler: gcc

addons:
  sonarcloud:
    organization: "algodat1"
  apt:
    packages:
      - graphviz
      - doxygen
      - doxygen-gui
      - doxygen-doc
      - doxygen-latex
    sources:
      - ubuntu-toolchain-r-test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
      branch: master

before_install:
  - pip install --user cpp-coveralls

before_script:
  - rm -rf build
  - mkdir build
  - cp sonar-project.properties build/
  - cd build
  - pwd && cmake ..

# Build steps
script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - make
  - test/testAVLTree
  - make doc
  - cd doc

after_success:
  - coveralls --root .. -E ".*googletest-src.*" -E ".*gtest.*" -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

cache:
  directories:
    - '$HOME/.sonar/cache'